HHPC <- read.table("household_power_consumption.txt", header= TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
HHPC<-HHPC[HHPC$Date %in% c("1/2/2007","2/2/2007"),]
dt <- strptime(paste(HHPC$Date, HHPC$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
png("plot3.png", width=480, height=480)
par(mfrow=c(1,1))
plot(dt,HHPC$Sub_metering_1,type="l",col="black",xlab="",ylab="Energy sub metering")
lines(dt,HHPC$Sub_metering_2,col="red")
lines(dt,HHPC$Sub_metering_3,col="blue")
legend("topright",  legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black","red","blue"),lwd=c(1,1,1))
dev.off()